// ============================================================
//  License system — configuration
// ============================================================
//
//  This file is the ONLY place you edit to wire the app to your
//  license server. The matching PRIVATE key NEVER ships with the
//  app — it lives only on your server (server/keys/private.pem).
//
//  How the "free now, lockable later" model works:
//    • The app ships with `defaultEnforce = false` → it is free.
//    • When the machine has internet it fetches a *signed* policy
//      from `serverUrl`. The policy says whether a license is
//      required. Today your server returns enforce=false.
//    • Months later, flip enforce=true in your admin panel. The
//      next time each user's machine is online, it pulls the new
//      signed policy and locks until a valid license is entered.
//
//  Because the policy and licenses are Ed25519-signed, a user
//  cannot forge "enforce=false" or a fake license without the
//  private key.
// ============================================================

export interface LicenseConfig {
  appId: string;
  appVersion: string;
  /** Base URL of your license server. No trailing slash. */
  serverUrl: string;
  /** Page where users register / buy a license. Opened from the lock screen. */
  purchaseUrl: string;
  /** Ed25519 public key (SPKI / PEM). Generated by `node server/keygen.mjs`. */
  publicKeyPem: string;
  /** How often to re-check the policy while online (ms). */
  pollIntervalMs: number;
  /** Network timeout for the policy fetch (ms). */
  fetchTimeoutMs: number;
  /**
   * Fallback when there is NO cached policy yet AND the server has
   * never been reached. `false` keeps the app free/unlocked.
   */
  defaultEnforce: boolean;
}

export const LICENSE_CONFIG: LicenseConfig = {
  appId: "com.labelstudio.app",
  appVersion: "1.0.0",

  // The policy now lives in Payload CMS (front/cms). The app polls
  // `${serverUrl}/api/license/policy`, which the CMS serves. Point this at
  // your CMS public origin before shipping a paid build.
  //   dev:  http://localhost:3001
  //   prod: https://cms.labelo.example.com
  serverUrl: "https://cms.labelo.example.com",
  // Where users register / manage devices to get a license key (the website).
  purchaseUrl: "https://labelo.example.com/register?redirect=/dashboard",

  // Public half of server/keys/private.pem. Safe to ship.
  publicKeyPem: `-----BEGIN PUBLIC KEY-----
MCowBQYDK2VwAyEANPPUNyoKCNsWW8jpiFKpLnZO5uuvId0B132iPCl8IWU=
-----END PUBLIC KEY-----`,

  pollIntervalMs: 6 * 60 * 60 * 1000, // 6 hours
  fetchTimeoutMs: 8000,

  // Free by default. Your server controls real enforcement.
  defaultEnforce: false,
};
